# This file is locked for GovCMS SaaS.
include:

  # This file allows some control of GitLab testing phases.
  - local: '/.gitlab-ci-defaults.yml'

  # The primary default GovCMS GitLab CI configuration.
#  - project: 'govcms/image-tooling'
#    ref: master
#    file: 'gitlab/.gitlab-ci-main.yml'

  # Replaces the above until something like https://github.com/simesy/scaffold-tooling in Gitlab.
  - 'https://raw.githubusercontent.com/simesy/scaffold-tooling/master/gitlab/.gitlab-ci-main.yml'
