# This file is locked for GovCMS SaaS.
include:

  # Starting inputs for the GitLab CI configuration.
  - local: '/.gitlab-ci-inputs.yml'

  # The primary default GovCMS GitLab CI configuration.
  - project: 'govcms/image-tooling'
    ref: master
    file: 'gitlab/.gitlab-ci-main.yml'
