# Basic control of your GitLab CI.
# @todo wiki page

# Linting and other unit tests (no fully loaded Drupal).
.static-tests:
  # when: manual
  allow_failure: true

# Behat and integration tests (fully loaded Drupal).
.integration-tests:
  # when: manual
  allow_failure: false

# You can add new variables if they don't exist in .gitlab-ci-main.yml.
.variables:
  EXAMPLE_VARIABLE: "Example value."
